version: "3.8"

services:
  app:
    container_name: devops-app
    image: devops-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
